FROM python

WORKDIR ./phase-0



COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt



COPY . .


ENTRYPOINT [ "python", "./main.py" ]

CMD [ "list" , "add" , "complete" , "delete" ]